# Generated by Django 5.2.1 on 2025-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='csv_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
