# Generated by Django 5.2.1 on 2025-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='csv_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
